version: 2
formats: []

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py
  
build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

python:
    install:
        - requirements: source/rtd_requirements.txt
        - method: pip
          path: .
