version: 2
formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
    install:
        - requirements: source/rtd_requirements.txt
        - method: pip
          path: .
